name: "e2e Tests Workflow"

on:
  workflow_dispatch:
    inputs:
      yml-config-path:
        required: true
        type: string
  workflow_call:
    inputs:
      yml-config-path:
        required: true
        type: string

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
          files: ${{ inputs.yml-config-path }}

      - name: Run e2e tests
        run: |
          npm ci
          echo "Using ${{ env.E2E_TESTS_ENDPOINT_URL }} as the endpoint url."
          E2E_ENDPOINT_URL="${{ env.E2E_TESTS_ENDPOINT_URL }}" npm run test:e2e
