name: "e2e Tests Workflow"

on:
  workflow_dispatch:
    inputs:
      e2e-endpoint-url:
        required: true
        type: string
  workflow_call:
    inputs:
      e2e-endpoint-url:
        required: true
        type: string

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run e2e tests
        run: |
          npm ci
          echo "Using ${{ inputs.e2e-endpoint-url }} as the endpoint url."
          E2E_ENDPOINT_URL="${{ inputs.e2e-endpoint-url }}" npm run test:e2e
