name: Lint Workflow

on:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # excludes master
      - "!release/*" # excludes release branches

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ENV: ci

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"
          cache: "npm"

      - name: Initialize npm
        run: |
          echo "//nexus.utility.decent.com/repository/decent-npm-releases/:_auth=$(echo -n ${{ secrets.NEXUS_READ_USER }}:${{ secrets.NEXUS_READ_PASS }} | openssl base64)" >> .npmrc
          echo "//nexus.utility.decent.com/repository/npm-central/:_auth=$(echo -n ${{ secrets.NEXUS_READ_USER }}:${{ secrets.NEXUS_READ_PASS }} | openssl base64)" >> .npmrc
          echo "always-auth=true" >> .npmrc
          echo "strict-ssl=true" >> .npmrc
          npm ci
      - run: npm run lint-check
