name: Lint Workflow

on:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # excludes master
      - "!release/*" # excludes release branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci
      - run: npm run lint-check
