name: "Trigger Build and Deployment"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "app.js"
      - "src/**"
      - "package-lock.json"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    with:
      yml-config-path: "deployment/config.yml"

  deploy-cloud-run:
    uses: ./.github/workflows/deploy-cloud-run.yml
    needs: docker-build
    with:
      yml-config-path: "deployment/config.yml"
